### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by DavidMChan**
Created PR for testing branch.

### CODE REVIEW

**Comment by DavidMChan** [comment]
Can we update this PR so that Tensorflow is an optional requirment? (Just guard the test with an import try/except.

**Comment by LutetiumX** [comment]
shall add tensorflow guard when writing test_dataset folders.

**Comment by LutetiumX** [comment]
New pull, the issue is when adding folder with datastore.  The default is copy all the information within the folder rather than the folder itself.  
i.e  src: work/folder/*-files.txt dst: .flux/key/folder/*files.txt 
rather than
src: work/folder*-files.txt dst: .flux/key/*-files.txt
(OPTIONAL: maybe add a check to copy the contents of the folder without the folder vs have the folder)

**Comment by LutetiumX** [comment]
Is there a command in msvscode that fixes the styling issue for you?

**Pull request merged**
